### ISSUE TITLE
Listagem de atividades prioritárias

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-org#80]
### Descrição
Listar todas as atividades previstas para que o evento ocorra. Definir datas e definir ciclos de entrega como [milestones](https://github.com/pythonbrasil/pybr2022-org/milestones). 

Temos 9 meses até o mês de outubro. Podemos dividir as milestones em ciclos de 3 meses até a data final do evento.

**Milestone 1:** 
Período: Fevereiro / Março /Abril

**Milestone 2:** 
Período: Maio / Junho / Julho

**Milestone 3:** 
Período: Agosto /Setembro / Outubro

### Requisitos para a atividade ser considerada como concluída

- [ ] Listar as todas as atividades nesse [documento](https://docs.google.com/spreadsheets/d/1B4H7Di94yto45nTOYmhoKtplWZiPKC1T-25bY8gLHN8/edit?usp=sharing)
- [ ] Definir datas de entrega para cada atividade
- [ ] Distribuir e criar as [milestones](https://github.com/pythonbrasil/pybr2022-org/milestones) no projeto.

**Comment by wasp-lahis** [comment]
Listei todas as atividades macro e micro do evento, colocando prioridades de 1-5. Com certeza vai surgir mais coisa, mas, por enquanto, me baseei no Quadro de issues e atas de reunião. 

Está em [documento](https://docs.google.com/spreadsheets/d/1B4H7Di94yto45nTOYmhoKtplWZiPKC1T-25bY8gLHN8/edit?usp=sharing)

Essa listagem pode ajudar a tornar as atividades assíncronas voltadas para prioridades + urgentes no momento. @giuliocc @julianyraiol @luizbenttes @cecivieira

**Comment by cecivieira** [comment]
@wasp-lahis acredito que deva ser incluída a atividade "planejamento das campanhas publicitárias", pois acredito que facilitará a definição das postagens necessárias, consequentemente, as entregas da equipe de design e a contratação da gestora de redes sociais.

Compartilho o planejamento das campanhas da pybr2021:

https://docs.google.com/spreadsheets/d/1ISo4dqdqoB1A2CRHCQSpZ06EWRnkutZWfCWCx7xHwz0/edit?usp=sharing

Aproveito para sugerir a inclusão das seguintes campanhas adicionais:
- Vacinação COVID e Febre Amarela (10 dias antes de viajar (fonte de informação: [Ministério da Saúde - Artigo](https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/f/febre-amarela-1) + [Ministério da Saúde - Artigo 2](https://www.saude.go.gov.br/noticias/2095-vacina-contra-febre-amarela-deve-ser-aplicada-10-dias-antes-da-viagem) + [Lista de municípios conforme áreas de recomendação para vacinação contra febre amarela](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjAorfxlIz2AhWxLLkGHR0eAzsQFnoECAQQAQ&url=https%3A%2F%2Fsbim.org.br%2Fimages%2Ffiles%2Fms-listamunicipios-fa.pdf&usg=AOvVaw1vIO5-4D1Q7L6olkdRyYJz)))
- Políticas para um evento seguro contra COVID #6
